Register page
300ms/html-forms pull request #1
Opened 2019-08-15 15:45 UTC by 300ms

Errors fixed and merged from testing branch ^^

2019-08-15 21:23 UTC, Oghenebrume50 commented
Reviewing......

2019-08-15 21:36 UTC, Oghenebrume50 requested changes
Hi guys good start on this project, I'll be pointing out some corrections.

### Intuit products
-  The products row is under the Intuit logo and above the form.
- It shows the Mint logo and text (logo on the left, text on the right).
-  It shows the Quickbooks logo and text (logo on the left, text on the right).
- It shows the Turbotax logo and text (logo on the left, text on the right).

##### Form
## Top
* [ ] It has a title `Create an Intuit account`.
* [ ] It has a description: `One account for everything Intuit, including Mint`.
* [ ] It has a `Learn More` link.

Also, the goal of this project is to replicate the original webpage, the current implementation does not do that please compare implementation with the original design

2019-08-15 21:41 UTC, Oghenebrume50 requested changes
Please fix these things and submit for re-review, feel free to chat me up on slack if there are issues

2019-08-15 21:41 UTC, Oghenebrume50 commented on index.html
> +                <fieldset class="fieldset">
This fieldset tag is not really needed here, what exactly are we grouping :thinking:

2019-08-16 21:29 UTC, Oghenebrume50 requested changes
![11](https://user-images.githubusercontent.com/37092867/63199019-713be200-c074-11e9-96cf-38feda8d9dc6.png)
![111](https://user-images.githubusercontent.com/37092867/63199024-74cf6900-c074-11e9-9c30-066f238b8a54.png)
Hi, team, the changes are good but we need to do a little more work, the screenshot above shows how your form displays and what is expected. Please pay attention to colours, size positioning. Basically replicate the design, good job so far, I am sure you guys can do it :+1:

2019-08-20 06:51 UTC, Oghenebrume50 requested changes
Hi good job on the corrections, however somethings were missed  
- The intuit logo was not added :smiley: 
- The key lock icon in the password field is still off, please align properly.
- The input fields and the button should be of same width, there should be equal space between them and the container on both sides, that is, they should be centered.

2019-08-20 06:54 UTC, Oghenebrume50 requested changes
Make these changes and submit for re-review :innocent:

2019-08-20 06:54 UTC, Oghenebrume50 commented on stylelint.config.js
> +    //"block-opening-brace-space-before": "always",
Please delete commented code, if this is affecting your development, just delete other than commenting it out

2019-08-20 06:54 UTC, Oghenebrume50 commented on stylelint.config.js
> +    /*"rule-empty-line-before": [ "always-multi-line", {
Please delete commented code

2019-08-30 23:59 UTC, uche-inyama requested changes
## Hi guys! everything looks almost fine. :raised_hands: :medal_sports: 
#### There are some observations:

- [x] Your html code is not passing the validation test, ensure that it does.
 
- [x] The intuit logo is not showing up, check it out. :microscope: :smile: 

#### Here is what your site looks like, there's no **Intuit logo**
![Screenshot from 2019-08-31 00-46-30](https://user-images.githubusercontent.com/46329537/64056136-0bc61600-cb89-11e9-9c23-14594075f59c.png)


#### Here is what the intuit site looks like
![Screenshot from 2019-08-31 00-46-13](https://user-images.githubusercontent.com/46329537/64056168-429c2c00-cb89-11e9-8d2a-ac934bd4c675.png)

#### Here's another observation, ensure that this sentence ``` One account for everything Intuit. Learn more``` is in a single line.


### Implement these changes and submit another review form, you are almost there :fire: :muscle:

2019-09-01 03:57 UTC, 300ms commented
Code passes from html validation now. The logo is visible and positioned, i don't know why why you can't see it, i added a screenshot here-exists in readme.md file too-, so you can see that logo exists and "Learn More" anchor text is in a new line.

2019-09-01 04:24 UTC, bolah2009 approved these changes
# Nice Job @300ms 

### Good Job implementing all suggested changes. It's a :+1: from me...

#### The [clone](https://raw.githack.com/300ms/html-forms/98aabfc8e835e9d7d2bb188300a97a6dd7105840/index.html) looks good to me, uses HTML forms elements effectively. :ok_hand: 

[OPTIONAL but strongly recommended] Refactor the code to keep asset (CSS or images) files in a separate directory. Currently, all files are in the root folder which may make it difficult to find a specific type of file especially when they become many.


Good luck with your next project. :star2: 

Cheers
[Bola](https://bolabuari.com/)  

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-10-01 15:40 UTC, merged